# generated by Gemini
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm # カラーマップ用

def load_csv(path: str):
    data = np.loadtxt(path, delimiter=',', skiprows=1)
    return data

def regression_analysis(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    # 擬似逆行列(pinv)を使って安定計算させる
    return np.linalg.pinv(x.T @ x) @ x.T @ y

def main():
    # データの読み込み
    data_path = "../data/advertising.csv"
    data = load_csv(data_path)

    X_org = data[:, :-1] # TV, Radio, Newspaper
    y = data[:, -1]      # Sales
    N = X_org.shape[0]

    # --- モデル構築（交互作用ありバージョン） ---
    # Bias, TV, Radio, Np, TV*Radio
    bias = np.ones((N, 1))
    tv_radio = (X_org[:, 0] * X_org[:, 1]).reshape(-1, 1)
    
    # 学習用データ行列
    X_train = np.hstack((bias, X_org, tv_radio))
    
    # パラメータ推定
    w = regression_analysis(X_train, y)
    
    # --- 可視化の準備 ---
    plt.figure(figsize=(10, 7))
    
    # 背景に元データを散布図として薄く描画
    plt.scatter(X_org[:, 0], y, color='gray', alpha=0.3, label='Actual Data')

    # TV（横軸）の範囲
    tv_axis = np.linspace(X_org[:, 0].min(), X_org[:, 0].max(), 100).reshape(-1, 1)
    
    # Newspaperは平均値で固定
    np_fixed = np.mean(X_org[:, 2])

    # ★ここがポイント：Radioの値を5段階に分けてグラデーション表示
    # 10%タイル(少) 〜 90%タイル(多) を5分割
    radio_levels = np.linspace(np.percentile(X_org[:, 1], 10), 
                               np.percentile(X_org[:, 1], 90), 
                               5)
    
    # カラーマップ（coolwarm: 青〜赤）を用意
    cmap = cm.get_cmap('coolwarm')
    
    print("--- Slope Analysis ---")
    print(f"Base TV Slope (beta_TV): {w[1]:.4f}")
    print(f"Interaction Boost (beta_TR): {w[4]:.4f}")
    print("-" * 30)

    for i, r_val in enumerate(radio_levels):
        # 色を決定 (0.0〜1.0正規化)
        color = cmap(i / (len(radio_levels) - 1))
        
        # 予測用データの作成
        _bias = np.ones((100, 1))
        _tv   = tv_axis
        _rad  = np.full((100, 1), r_val)
        _np   = np.full((100, 1), np_fixed)
        _inter= _tv * _rad # ここで相乗効果が効いてくる
        
        X_pred = np.hstack((_bias, _tv, _rad, _np, _inter))
        
        # 予測値計算
        y_pred = X_pred @ w
        
        # 傾きを計算してラベルに表示してみる (beta_TV + beta_TR * Radio)
        slope = w[1] + w[4] * r_val
        label = f"Radio: {r_val:.1f} (Slope: {slope:.3f})"
        
        plt.plot(tv_axis, y_pred, color=color, linewidth=2.5, label=label)

    # グラフ装飾
    plt.title("Visualizing Interaction Effect: The 'Fan' Shape\n(Higher Radio -> Steeper Slope)", fontsize=14)
    plt.xlabel("TV Ad Spend")
    plt.ylabel("Sales")
    plt.legend(title="Radio Spend Level")
    plt.grid(True, linestyle='--', alpha=0.6)
    
    plt.tight_layout()
    plt.savefig(f'../outputs/hikaku.png')

if __name__ == "__main__":
    main()